name: 'Download artifact'
description: 'Download workflow artifacts'
author: 'GitHub'
inputs: 
  name:
    description: 'Artifact name'
    required: true
  path:
    description: 'Destination path'    
runs:
  # Plugins live on the runner and are only available to a certain set of first party actions.
  plugin: 'download'
